# Содержит информацию о пакетах для генерации соответствующих им Markdown-файлов
# Связан с конфигом `packages.toml`: оттуда берутся доп. сведения вроде описания
# пакета и его версии

# Структура конфига:
# [[package]]
# id = "имя созданного md-файла"
# package = "имя пакета из файла packages.toml"
# sbu = 1 # ОВС
# dir_pth = "в какой директории сохранить файл описания пакета"

[[package]]
id = "binutils"
package = "binutils"
sbu = 1
dir_pth = "cross-compiler"

[[package]]
id = "gcc-p1"
package = "GCC"
sbu = 14.8
dir_pth = "cross-compiler"

[[package]]
id = "gcc-p2"
package = "GCC"
sbu = 14.8
dir_pth = "cross-compiler"

[[package]]
id = "musl"
package = "musl"
sbu = 5.4
dir_pth = "cross-compiler"

[[package]]
id = "linux-headers"
package = "Linux"
description = "Заголовочные файлы ядра Linux, необходимые для сборки кросс-компилятора"
sbu = "0.5"
dir_pth = "cross-compiler"

[[package]]
id = "linux"
package = "Linux"
sbu = 666
dir_pth = "kernel"

[[package]]
id = "libgcc"
package = "GCC"
description = "При компиляции динамических библиотек с помощью GCC требуется, чтобы `libgcc` могла быть загружена во время выполнения программы. Поэтому нам нужно скопировать библиотеку `libgcc`, которая ранее была собрана для кросс-компилятора."
sbu = 0
dir_pth = "base"

[[package]]
id = "musl"
package = "musl"
sbu = 1
dir_pth = "base"

[[package]]
id = "lfa_init"
package = "lfa_init"
sbu = 10
dir_pth = "base"

[[package]]
id = "busybox"
package = "BusyBox"
sbu = 1
dir_pth = "base"

[[package]]
id = "iana-etc"
package = "iana-etc"
sbu = 0.01
dir_pth = "base"

[[package]]
id = "u-boot"
package = "u-boot"
sbu = 10
dir_pth = "bootloader"
