name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make install-deps

    - name: Build book
      run: make

    - name: Copy PDF file to project root
      run: make pdf

    - name: Commit changes
      run: git commit -m "Generate utput.pdf file"

    - name: Push changes
      run: git push origin HEAD:master
